name: Phoenixio
favicon: null
layout_spectrum: 0.9551150351762772
typography_spectrum: 0.7294327630661428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4079c6'
    - '#11213a'
    - '#9f1120'
    - '#a94126'
    - '#b28d5c'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
